### ISSUE TITLE
Maqqaf recognition

### ISSUE THREAD

**Issue by yarons** [tesseract-ocr/langdata#129] opened 2018-07-05 11:48 UTC
https://github.com/tesseract-ocr/langdata/blob/106c9b31bea9d30814fc116cbcb9c267dee7df70/heb/heb.numbers#L13

There are numerous options with - (ב-, כ-, ל-‏) while in Hebrew there are cases where proper Maqqaf is used (ב־3 מתוך 4 מקרים).

With this dataset it will not be identified or tested.

**Comment by amitdo** [comment] 2018-07-05 12:46
Duplicate of: https://github.com/tesseract-ocr/langdata/issues/82#issuecomment-320507304

**Comment by amitdo** [comment] 2019-02-27 14:16
@zdenop, please close this issue.

**Closed** 2019-02-27 14:46 UTC
